#!/bin/bash
#git ls-files --others -i --exclude-standard | grep "SECURE_*" | xargs git add -f 

if [ $# -eq 0 ]; then
    echo -e "Commit message must be supplied"
    exit
fi

git add .
git ls-files | grep "SECURE_*" | xargs git rm --cached
git commit -m "$1"
git push origin master

git add .
git commit -m "$1"
git push heroku master
